# Generated by Django 5.1.5 on 2025-01-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_alter_quiz_created_by_alter_quiz_total_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('Science', 'Science'), ('History', 'History')], max_length=50),
        ),
    ]
